### ISSUE TITLE
Create YAML file(s) with navigation goal poses

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/metacontrol_sim#11]

**Comment by marioney** [comment]
yaml file created on https://github.com/rosin-project/metacontrol_sim/commit/ab72ef2e15b4180230974733f1498d34850eaac8

@chcorbato  can you check it? and if it's OK close this

**Comment by marioney** [comment]
I've tested it using
```
roscd metacontrol_sim && rostopic pub -f yaml/goal.yaml move_base_simple/goal geometry_msgs/PoseStamped --once
```
And seems to work

**Comment by marioney** [comment]
Tested now with the `rosgraph_manipulator`
