### ISSUE TITLE
Create observer for safety

### ISSUE THREAD

**Issue by darkobozhinoski** [rosin-project/metacontrol_sim#18]
The model of safety is taken from this [reference](http://reason.cs.uiuc.edu/jaesik/papers/TIE_ChungWChoiJSongJ.pdf).

Safety observer is defined [here](https://github.com/rosin-project/rosgraph_monitor/blob/observers/src/rosgraph_monitor/observers/safety_quality_observer.py).

Run-time safety is calculated as follows: 
 S= {
            1,         if P > d_break;
            P_r/d_break,       otherwise;                               …. (Eq1)
}       
where: 

- P  - a distance from a current location of the robot to the closest obstacle in the robot direction.
- P_r = P - inflation_radius
- d_break is the breaking distance of the robot before hitting an obstacle; 

Furthermore:

- P is computed from the laser scans;
- d_break = v^2*r /(2 × a_robot)   … (Eq2) where:
         * v - the current speed of the robot;
         * a_robot - the acceleration of the robot;
         * r  - Radius of the robot ;

**Comment by chcorbato** [comment]
@darkobozhinoski please add the basic info on how this issue is resolved, e.g. link to code and instructions for the safety observer

**Comment by chcorbato** [comment]
- Where is the definition of the observation model (i.e. the equation implemented in the observer)
- How is the acceleration computed?

**Comment by darkobozhinoski** [comment]
The model of safety is taken from this [reference](http://reason.cs.uiuc.edu/jaesik/papers/TIE_ChungWChoiJSongJ.pdf).

Safety observer is defined [here](https://github.com/rosin-project/rosgraph_monitor/blob/observers/src/rosgraph_monitor/observers/safety_quality_observer.py).

Run-time safety is calculated as follows: 
 S= {
            1                                  if P > d_break;
            P_r/d_break                           otherwise;                               …. (Eq1)
}       
where: 

- P  - a distance from a current location of the robot to the closest obstacle in the robot direction.
- P_r = P - inflation_radius
- d_break is the breaking distance of the robot before hitting an obstacle; 


Furthermore:

- P is computed from the laser scans;
- d_break = v^2*r /(2 × a_robot)   … (Eq2) where:
         * v - the current speed of the robot;
         * a_robot - the acceleration of the robot;
         * r  - Radius of the robot ;

**Comment by darkobozhinoski** [comment]
> * Where is the definition of the observation model (i.e. the equation implemented in the observer)
> * How is the acceleration computed?
I reported the definition of the observer in my previous comment.
For acceleration, we might calculate from here:  http://docs.ros.org/melodic/api/sensor_msgs/html/msg/Imu.html  or we can "simplify" our model and remove it from our equation.

**Comment by darkobozhinoski** [comment]
> @darkobozhinoski please add the basic info on how this issue is resolved, e.g. link to code and instructions for the safety observer

done :)

**Comment by chcorbato** [comment]
> > * Where is the definition of the observation model (i.e. the equation implemented in the observer)
> > * How is the acceleration computed?
> 
> I reported the definition of the observer in my previous comment.
> For acceleration, we might calculate from here: http://docs.ros.org/melodic/api/sensor_msgs/html/msg/Imu.html or we can "simplify" our model and remove it from our equation.

As you say, we can compute it from the IMU sensor that looks like we have in the simulation (part of the ridgeback real robot too?):
topic: `/imu/data`
message fields needed `linear_acceleration.x` and `linear_acceleration.y` , and then apply Pithagoras theorem I guess
