### ISSUE TITLE
rosgraph_manipulator cannot execute reconfiguration when launched in the same terminal 

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/metacontrol_sim#20]
I have tested d92e96e348b5839754d08d885c85cfc90ec4ffa6 and `mros1_reasoner` gets stuch waiting for the result of the reconfiguration action.
I guess something goes wrong with `rosgraph_manipulator` 
I have tested it launching MVP_ commenting the following line:
https://github.com/rosin-project/metacontrol_sim/blob/d92e96e348b5839754d08d885c85cfc90ec4ffa6/launch/MVP_metacontrol_world.launch#L55
and then launching the metacontrol nodes in `rosgraph_nodes.launch.xml` in separate terminals and **then it works!** see #14

**Comment by marioney** [comment]
@chcorbato can you tell us the sequence of commands that you're using to launch everything? I mean,  Do you launch the reasoner first? and which onto file are you launching?

**Comment by marioney** [comment]
Solved in https://github.com/rosin-project/metacontrol_sim/commit/0b9dbd0ea1149beb8b95074579033686e87e4a73
