### ISSUE TITLE
add kinect model to ridgeback

### ISSUE THREAD

**Issue by marioney** [rosin-project/metacontrol_sim#24]
In order to manage component failure, and reconfiguration, a Kinect model needs to be added to the ridgeback.

@chcorbato should we have a different field of view / range or use the same as the laser? 

Since we're using fake_localization it only needs to be configured for navigation

**Comment by chcorbato** [comment]
> @chcorbato should we have a different field of view / range or use the same as the laser?

I think it should be realistic to what the actual field of view and range is for the 3D sensor.
I suggest we add something reasonable, not necessarily the kinect, but maybe a `realsense`
I suggest the following criteria for this decision:
- be realistic - ABB is actually using `realsense` 
- be easy to add (e.g. existing model for [gazebo](https://github.com/intel/gazebo-realsense))
what do you think @marioney ?

**Comment by marioney** [comment]
Solved in https://github.com/rosin-project/metacontrol_sim/commit/b5248dbcf7e4d93916d5555c229aa7e19fefbe2d
