### ISSUE TITLE
Data logging tool for the experiments

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/metacontrol_sim#25]
This is needed for #26

**Comment by marioney** [comment]
@chcorbato @darkobozhinoski what data should we log? 

I'm listing here some, but please feel free to add / remove anything that may be needed

- robot position x: From `/amcl_pose` topic
- robot position y: From `/amcl_pose` topic
- robot orientation:  From `/amcl_pose` topic ? ? 
- battery power load: From `/power_load` topic 
- linear velocity x: From `/odom` topic 
- linear acceleration x: From `/imu_data` topic 
- line: From `/imu_data` topic 
- distance to closest obstalce: Form `/d_obstacle topic`
- QA Energy:  From `/diagnostics` topic
- QA Safety:  From `/diagnostics` topic

**Comment by darkobozhinoski** [comment]
@marioney , we will also need to log the time. 
With this, we can measure the total time to complete the mission, the time that certain attribute was under a safety/energy threshold etc. 
@marioney , we should also measure how many times reconfiguration have been mane (we purposely killed the move_base). 
The rest looks good to me.

**Comment by chcorbato** [comment]
> I'm listing here some, but please feel free to add / remove anything that may be needed

Maybe it is handy to log when the nav goal is sent and when it is achieved, I think `/move_base/goal` and `/move_base/result`\
I already added this to the list

> @marioney , we will also need to log the time.

ROS messages (whet we will log), include a header with a timestamp
- [ ] we need to check that all our publishers (for metacontrol) are setting that header see #30

**Comment by gavanderhoorn** [comment]
> ROS messages (whet we will log), include a header with a timestamp

Nuance: only those messages which have a `std_msgs/Header`.

You don't get anything for free here.

If you don't have a header, you'll only be able to approximate things with `ros::Time::now()`, which is suboptimal.

**Comment by chcorbato** [comment]
I think for the moment this is implemented ad-hoc for our current experiments in #26 
I'm triaging it as `enhancement` and for later in our [project board](https://github.com/orgs/rosin-project/projects/2)
