### ISSUE TITLE
Create basic experimental setup to run and obtain data

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/metacontrol_sim#26]
Just 2 workstations (goals) - try with the factory map (desired), but if problematic use the map we have.

Should follow the definition in https://github.com/rosin-project/metacontrol_nav/issues/4

Needs:
- [x] Data logging tool #25 
- [x] Create factory environment
- [x] Define Goal positions - a set of 3 values
- [x] Define Initial positions - a set of 3 values
- [x] Create map - only one is going to be used
- [x]  Define launch configuration: - a set of 3 configurations (Fast / Standard / Safe)
- [x] Create control script for the experiments: #29

**Comment by marioney** [comment]
Factory environment is created in #27  and the factory map is created in https://github.com/rosin-project/metacontrol_nav/commit/8f57deac1e2f94a67ba1e3ac827c163b59cf961b

**Comment by marioney** [comment]
3 Goal positions and 3 Start positions are defined in the image
![factory_goals](https://user-images.githubusercontent.com/5198223/81923247-a498a680-95dd-11ea-95a8-34de59d23c17.png)

@chcorbato @darkobozhinoski  does theses position seem ok to you?

**Comment by chcorbato** [comment]
> 3 Goal positions and 3 Start positions are defined in the image
> ![factory_goals](https://user-images.githubusercontent.com/5198223/81923247-a498a680-95dd-11ea-95a8-34de59d23c17.png)
> 
> @chcorbato @darkobozhinoski does theses position seem ok to you?

Looks good to me!

**Comment by chcorbato** [comment]
In the current setup:
`metacontrol_sim`:https://github.com/rosin-project/metacontrol_sim/commit/6d9e3d015e202988e3b6a793531e4b1be37d71d6 `metacontrol_nav:`https://github.com/rosin-project/metacontrol_nav/commit/fa078c4f0c39f87c69fc4ed6de1fe2702f646197

The metacontrol correctly triggers adaptation (see below Observation energy above `1.5` threshold) changing from the departing configuration and switching to ``, and resumes navigation towards current goal, but gets stuck (see image)
`fg_nav_fast      None    [('obs_energy_1', 2.04421472549), ('obs_energy_2', 1.65799868107), ('obs_energy_3', 2.33954739571), ('obs_energy_4', 1.47190856934), ('obs_energy_5', 1.46199381351)]`
![rviz_screenshot_2020_05_14-14_41_14](https://user-images.githubusercontent.com/9592617/81936288-4de99780-95f2-11ea-960f-1b740e3be275.png)

**Comment by marioney** [comment]
>  resumes navigation towards current goal, but gets stuck (see image)

I've just checked and I have the same error. Seems that the local planner is ignoring the global plan. I'll try to fix that

**Comment by chcorbato** [comment]
> @chcorbato can you test with that value and report back.

It works for me too, also with metacontrol adapting half-way. Do you want me to help testing with other start and goal positions?

**Comment by chcorbato** [comment]
In relation to:
> * Define launch configuration: - a set of 3 configurations (Fast / Standard / Safe)

Is this done/ready?

Additionally:
I think that currently configurations correspond to different   values `{'safe','standard','fast'}` for the argument `profile` in the launch file:
[`metacontrol_nav/launch/include/move_base.launch`](
https://github.com/rosin-project/metacontrol_nav/blob/master/launch/include/move_base.launch)

But in principle @ipa-nhg is generating different launch files for each configuration.
We need to fix a way to proceed with this, because it affects the implementation of [`rosgraph_manipulator`](https://github.com/rosin-project/metacontrol_sim/blob/MVP_world/scripts/rosgraph_manipulator.py)

**Comment by marioney** [comment]
> I think that currently configurations correspond to different values `{'safe','standard','fast'}` for the argument `profile` in the launch file:

You're right, these are the configurations. 

> But in principle @ipa-nhg is generating different launch files for each configuration.
> We need to fix a way to proceed with this, because it affects the implementation of [`rosgraph_manipulator`](https://github.com/rosin-project/metacontrol_sim/blob/MVP_world/scripts/rosgraph_manipulator.py)

Does the `reasoner` need to know the current (initial) configuration beforehand?  Or can we start with one of those three and perform reconfiguration then?  In any case, we can use the launch files generated by @ipa-nhg, we just need to include them onthe `metracontrol_sim` main launch file.

**Comment by chcorbato** [comment]
> Does the `reasoner` need to know the current (initial) configuration beforehand? Or can we start with one of those three and perform reconfiguration then?

> In any case, we can use the launch files generated by @ipa-nhg, we just need to include them on the `metracontrol_sim` main launch file.

That is ok, but I think this only affects how the experiments are deployed. There are two uses of these files:
- metacontrol uses them as resources to execute adaptations. For this it is important to standardize where(folder) are those files located and how they are named.
  - where do you think we should have them in `metacontrol_sim` or in `metacontrol_nav`? @marioney @ipa-nhg 
- deploy the navigation application for the experiments (this is what you mention in your comment). Ideally, we do not have the files in two places, but just use the same ones.

**Comment by chcorbato** [comment]
Setup ready, obtaining the data is https://github.com/rosin-project/mros1_reasoner/issues/10#issuecomment-630073391
