### ISSUE TITLE
Adapt rosgraph_manipulator to reconfigure using launch files generated by RosModel

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/metacontrol_sim#35]
This is what we discussed today.
Currently the reconfiguration uses a single launch file and a launch argument to select amongst predefined param configs for move base.
See:
https://github.com/rosin-project/metacontrol_sim/blob/ae7ff41e65bfa2fcf1fa101e5ee3e99f92c597bb/scripts/rosgraph_manipulator.py#L136

What we need is to launch the launch files autogenerated from the .rossystem files of each configuration.

These files have the name and they are in a package both with the name of the configuration, which can be retrieved from the goal field `desired_configuration_name`
see: [metacontrol_msgs/action/MvpReconfiguration.action](https://github.com/rosin-project/metacontrol_msgs/blob/master/action/MvpReconfiguration.action#L12)

These lines also need to be changed: https://github.com/rosin-project/metacontrol_sim/blob/ae7ff41e65bfa2fcf1fa101e5ee3e99f92c597bb/scripts/rosgraph_manipulator.py#L100-L117

**Comment by ipa-nhg** [comment]
Solved by https://github.com/rosin-project/metacontrol_sim/pull/36

**Comment by chcorbato** [comment]
We need to complete #36 according to @marioney's [comment](https://github.com/rosin-project/metacontrol_sim/pull/36#issuecomment-631605601)
but I close this issue
