### ISSUE TITLE
Create code for Objective Error observer

### ISSUE THREAD

**Issue by marioney** [rosin-project/metacontrol_sim#40]
Observer for Objective error: needed for scenarios 3 in yellow table 

- Should check if there's an error when the route is not available. 
      - `Path` length 0  
- Check `move_base/result` topic
- Should check if the robot is blocked (not moving after X seconds)

Objective should publish: "true" if there's an error
                                         "false" if the system is running OK.

Also create another another observer on the `rosgraph_observer` to send it to the reasoner

https://docs.google.com/document/d/1BaOxo7_WQ2fUUUWIyw5pE_K_q6sErQJXge5VeFjyhgQ/edit#bookmark=id.4rg7xmp249au

**Comment by marioney** [comment]
@darkobozhinoski  @chcorbato A quick question, if an error is received, the message is sent but when should we clear the objective error (change the error message to false again)

Options are: 

- When a new goal (reconfiguration) is received
- Only send the error one time
- Keep the error for X seconds

**Comment by marioney** [comment]
Done in https://github.com/rosin-project/metacontrol_sim/commit/87ad4e04383265bc03cbd1468b641b4ae3b3df4f and https://github.com/rosin-project/rosgraph_monitor/commit/674fc297aa8b28a0a7af40c79871a8af27ea026a

>     * Keep the error for X seconds

For now the error message is published for 1 sec.

**Comment by chcorbato** [comment]
> @darkobozhinoski @chcorbato A quick question, if an error is received, the message is sent but when should we clear the objective error (change the error message to false again)

I am not sure.
> Options are:
> * When a new goal (reconfiguration) is received
> * Only send the error one time
> * Keep the error for X seconds

Nice analysis. I would say the error should be reported while the condition that triggered it continuous. If the topics whose values cause it keep reporting the same values, keep sending the error. But it is just an idea.

**Comment by marioney** [comment]
@chcorbato should we close this?

**Comment by chcorbato** [comment]
I think I remember seeing the error in the printout of the message received by `mros1_reasoner` with "ojbective" misspelled. A part from that, yes, you can close it.

**Comment by chcorbato** [comment]
Current solution rosin-project/rosgraph_monitor@674fc29 needs improvements

Ad-hoc code:

https://github.com/rosin-project/rosgraph_monitor/blob/674fc297aa8b28a0a7af40c79871a8af27ea026a/src/rosgraph_monitor/observers/objetive_error_observer.py#L8

https://github.com/rosin-project/rosgraph_monitor/blob/674fc297aa8b28a0a7af40c79871a8af27ea026a/src/rosgraph_monitor/observers/objetive_error_observer.py#L16-L18

The mapping of the Objective error information needs re-thinking:
https://github.com/rosin-project/rosgraph_monitor/blob/674fc297aa8b28a0a7af40c79871a8af27ea026a/src/rosgraph_monitor/observers/objetive_error_observer.py#L20-L25
```
 status_msg = DiagnosticStatus()
        status_msg.level = DiagnosticStatus.OK
        status_msg.name = self._id
        status_msg.values.append(
            KeyValue("objetive_error", attr))
        status_msg.message = "QA status"
```

**Comment by chcorbato** [comment]
@ipa-hsd could you please transfer this issue to https://github.com/rosin-project/rosgraph_monitor/
I think it belongs there, but that repo is not listed for me when I try to transfer the issue.
