### ISSUE TITLE
Missing dependency: ridgeback_gazebo

### ISSUE THREAD

**Issue by JWijkhuizen** [rosin-project/metacontrol_sim#46]
In this package in the MVP branch, the dependency ridgeback_gazebo is missing in package.xml.

This results in a working simulation, except that the robot cannot move

**Comment by chcorbato** [comment]
@JWijkhuizen could you try to make a pull request to fix it?

**Comment by JWijkhuizen** [comment]
Yes I did now. Please let me know if I did not do it correctly

**Comment by chcorbato** [comment]
This issue can be closed once the pull request is approved and merged.
That is how the workflow should go.

**Comment by JWijkhuizen** [comment]
Thanks for the feedback.

This issue is fixed by #47 now, and is successfully merged and closed.
