### ISSUE TITLE
Define MVP world

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/metacontrol_sim#5]
define a launchfile for the world in the MVP scenario

**Comment by marioney** [comment]
@chcorbato should the MVP launch the navigation by default?  I guess this is linked with https://github.com/rosin-project/mros1_reasoner/issues/11 because we need to define what is changed or what is the starting point (what nodes need to be active before from the beginning)

**Comment by chcorbato** [comment]
I think for the moment we can have an initial launch taking care of launching the entire system, including navigation in standard mode.

**Comment by marioney** [comment]
The MVP world and launchers have been created on https://github.com/rosin-project/metacontrol_sim/commit/1f084a50d137dc96aaebf5702df9ff7e49cdb206

We should use the https://github.com/rosin-project/metacontrol_sim/tree/MVP_world branch
