### ISSUE TITLE
Create observer for the power consumption

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/metacontrol_sim#6]
Fake one but based on Harsh observer
Requirement is to output the proper [diagnostic message](https://github.com/ipa-hsd/rosgraph_monitor/pull/8#issuecomment-620464644)

**Comment by marioney** [comment]
The input topic should be `/power_load` it's being published by the battery load controller  (see #8  )

**Comment by chcorbato** [comment]
@darkobozhinoski can you point to the code that addresses this issue?

**Comment by darkobozhinoski** [comment]
@chcorbato https://github.com/rosin-project/rosgraph_monitor/blob/observers/src/rosgraph_monitor/observers/quality_observer.py

You can subscribe to the /diagnostics topic. 

https://github.com/rosin-project/rosgraph_monitor/blob/observers/src/rosgraph_monitor/observer.py

**Comment by chcorbato** [comment]
@darkobozhinoski do you confirm that we can close this issue?

**Comment by chcorbato** [comment]
See https://github.com/rosin-project/rosgraph_monitor/blob/observers/src/rosgraph_monitor/observers/energy_quality_observer.py
